Repository FRONTENDBOOTCAMP-11th/ShareFood, pull requests merged in 2024-12, with the labels that each got.

#40 ✨ List Components
  package.json
  public/images/char.svg
  public/images/like0.svg
  public/images/like1.svg
  public/images/map.svg
  public/images/pack.svg
  public/images/price.svg
  public/images/time.svg
  src/App.tsx
  src/components/List.tsx
  src/types/listComponentTypes.ts
  tailwind.config.js
  tailwind.config.ts
Labels: feature

#46 ✨ Image Slide 컴포넌트
  public/images/banner/banner1.png
  public/images/banner/banner2.png
  public/images/icons/next.svg
  public/images/icons/prev.svg
  src/components/ImageSlide.tsx
  src/components/List.tsx
  tailwind.config.ts
Labels: feature

#49 ✨ 메인페이지 - 헤더 및 배너
  index.html
  public/images/greenchef.svg
  public/images/icons/search.svg
  src/App.tsx
  src/components/Header.tsx
  src/components/ImageSlide.tsx
  src/pages/main/main.tsx
  src/router.tsx
Labels: feature

#50 🎨 feat[#34]: Modal 컴포넌트
  src/components/Modal.tsx
  tailwind.config.ts
Labels: feature

#51 🎨 feat[#35]: 공구, 판매 구분 컴포넌트
  src/components/PostType.tsx
Labels: feature

#53 🎨 메인페이지 UI 퍼블리싱
  public/images/icons/check-active.svg
  public/images/icons/check.svg
  src/App.tsx
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/List.tsx
  src/components/Select.tsx
  src/components/TypeSelector.tsx
  src/pages/main/main.tsx
  tailwind.config.ts
Labels: feature

#65 🎨 [Feat] 마이페이지 회원정보
  src/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/pages/myPage/myPage.tsx
Labels: feature

#66 💄 feat[19]: 마이페이지 게시물 카테고리에 따른 렌더링
  src/pages/main/main.tsx
  src/pages/myPage/myPage.tsx
Labels: feature

#67 💄 feat[20]: 로그아웃 버튼
  src/components/Button.tsx
  src/pages/myPage/myPage.tsx
Labels: feature

#71 💄 feat[#42]: 글 작성 내부 재사용 컴포넌트
  public/images/icons/empty_heart.svg
  public/images/icons/full_heart.svg
  public/images/logos/default_image.svg
  src/components/Comment.tsx
  src/components/CommentAdd.tsx
  src/components/CommentItem.tsx
  src/components/Total.tsx
Labels: feature

#81 🎨 feat[70]: 회원 정보 수정 페이지
  public/images/icons/arrow.svg
  public/images/icons/gallery.svg
  src/pages/myPage/UserInfo.tsx
  src/pages/myPage/myPage.tsx
  src/router.tsx
Labels: feature

#83 💄feat[#75] : 글 상세 페이지 퍼블리싱
  public/images/close.svg
  public/images/logos/detail_default_image.svg
  public/images/member.svg
  public/images/sample/grape1.jpg
  public/images/sample/grape2.jpg
  src/components/Comment.tsx
  src/components/CommentAdd.tsx
  src/components/CommentItem.tsx
  src/components/ImageSlideDetail.tsx
  src/components/Total.tsx
  src/pages/detail/detail.tsx
Labels: feature

#96 💄 select 컴포넌트 크기 수정
  src/components/Select.tsx
  src/pages/main/main.tsx
Labels: enhancement, feature

#100 💄 글 작성 페이지 퍼블리싱
  public/images/photo.svg
  src/components/ImageUpload.tsx
  src/components/Total.tsx
  src/pages/detail/detail.tsx
  src/pages/search/search.tsx
  src/pages/write/write.tsx
  tailwind.config.ts
Labels: feature

#109 🎨글 상세보기, 글 작성, 모달 스타일 수정
  src/App.tsx
  src/components/Comment.tsx
  src/components/CommentAdd.tsx
  src/components/CommentItem.tsx
  src/components/ImageUpload.tsx
  src/components/Modal.tsx
  src/components/Total.tsx
  src/components/TypeSelector.tsx
  src/pages/detail/detail.tsx
  src/pages/write/write.tsx
  tailwind.config.ts
Labels: enhancement

#123 💄feat[13]: 글 상세보기 내용 출력
  public/images/sample/grape1.jpg
  public/images/sample/grape2.jpg
  src/components/ImageSlideDetail.tsx
  src/pages/detail/detail.tsx
Labels: feature
