Repository FRONTENDBOOTCAMP-11th/ShareFood, pull requests merged in 2025-01, with the labels that each got.

#128 ✨ 메인페이지 - 리스트 호출 및 스타일 변경
  public/images/tag/time.svg
  src/App.tsx
  src/components/List.tsx
  src/components/PostType.tsx
  src/components/Tag.tsx
  src/pages/main/main.tsx
  src/types/listComponentTypes.ts
  src/types/productsTypes.ts
Labels: feature

#131 ✨게시물 필터링
  src/components/List.tsx
  src/components/Select.tsx
  src/components/TypeSelector.tsx
  src/hooks/useGetList.ts
  src/pages/main/main.tsx
  src/types/productsTypes.ts
Labels: feature

#133 💄 [#16] useParams Test 중간 merge
  src/components/Comment/Comment.tsx
  src/components/Comment/CommentItem.tsx
  src/components/Total.tsx
  src/pages/detail/detail.tsx
  src/router.tsx
Labels: help wanted

#134 ✨ 게시물 클릭시 해당 게시물 상세보기로 이동
  src/components/List.tsx
  src/pages/detail/detail.tsx
  src/pages/main/main.tsx
  src/pages/myPage/myPage.tsx
  src/types/listComponentTypes.ts
  src/types/productsTypes.ts
Labels: feature

#140 feat[#136]: 로그인 상태 에러 종류별로 메세지 내용 변경
  src/pages/login/login.tsx
Labels: feature

#142 ✨회원정보 조회
  src/components/ImageSlide.tsx
  src/components/List.tsx
  src/hooks/useGetList.ts
  src/hooks/useGetUserInfo.ts
  src/pages/login/login.tsx
  src/pages/main/main.tsx
  src/pages/myPage/UserInfo.tsx
  src/pages/myPage/myPage.tsx
  src/types/userInfoTypes.ts
Labels: feature

#143 feat[#141] : 로그인 데이터 스토리지 저장
  src/pages/login/login.tsx
  src/store/authStore.ts
Labels: feature

#149 🐛 axiosInstance 토큰 수정 및 라우트 수정
  src/hooks/axiosInstance.ts
  src/hooks/useGetList.ts
  src/pages/myPage/UserInfo.tsx
  src/pages/myPage/myPage.tsx
  src/router.tsx
Labels: bug

#162 ✨ 마이페이지 - 게시글 불러오기
  api/dbinit-sample/openmarket/data.js
  src/components/List.tsx
  src/hooks/axiosInstance.ts
  src/hooks/useGetList.ts
  src/pages/myPage/myPage.tsx
  src/store/listStateStore.ts
  src/types/listComponentTypes.ts
  src/types/productsTypes.ts
Labels: feature

#163 💄feat[16] : 글 상세 - 댓글 추가
  src/components/Comment/CommentAdd.tsx
  src/components/Modal.tsx
  src/components/Tag.tsx
  src/components/Total.tsx
  src/pages/detail/detail.tsx
Labels: feature

#164 ✨ 상세보기 접속 후 다시 리스트로 복귀시 필터 상태 유지
  src/components/List.tsx
  src/pages/main/main.tsx
  src/pages/myPage/modifiyInfo.tsx
  src/pages/myPage/myPage.tsx
  src/pages/search/searchPage.tsx
  src/pages/signUp/signUp.tsx
  src/router.tsx
  src/store/listStateStore.ts
Labels: enhancement

#170 ✨feat[#169]: 회원가입 유저 타입 seller 고정
  src/pages/signUp/signUp.tsx
Labels: feature

#174 💄feat[#17] : 글 상세 - 구매하기 기능
  src/components/Button.tsx
  src/components/CheckOrder/CheckBuyList.tsx
  src/components/CheckOrder/CheckBuyListItem.tsx
  src/components/Counter.tsx
  src/components/Modal.tsx
  src/pages/detail/detail.tsx
Labels: feature

#182 ✨마이페이지 회원 정보 수정
  src/components/Button.tsx
  src/components/Layout/Footer.tsx
  src/hooks/isDuplicate.ts
  src/hooks/useGetList.ts
  src/hooks/useGetUserInfo.ts
  src/hooks/useUploadImg.ts
  src/pages/myPage/modifiyInfo.tsx
  src/pages/myPage/modifyInfo.tsx
  src/pages/myPage/myPage.tsx
  src/pages/signUp/signUp.tsx
  src/router.tsx
Labels: feature

#184 ✨enhance: 글 상세 - 버튼 fixed 및 예외 사항 조치 추가
  src/components/Comment/CommentAdd.tsx
  src/pages/detail/detail.tsx
Labels: enhancement

#190 fix: db 정보 수정
  api/dbinit-sample/openmarket/data.js
  api/dbinit-sample/openmarket/uploadFiles/default1.png
  api/dbinit-sample/openmarket/uploadFiles/default2.png
  api/dbinit-sample/openmarket/uploadFiles/default3.png
  api/dbinit-sample/openmarket/uploadFiles/default4.png
  api/dbinit-sample/openmarket/uploadFiles/geonwoo.png
  api/dbinit-sample/openmarket/uploadFiles/hyunjong.png
  api/dbinit-sample/openmarket/uploadFiles/sunjae.png
  api/dbinit-sample/openmarket/uploadFiles/yujin.png
Labels: enhancement

#193 ✨enhance: 글 상세 - 로딩 중 컴포넌트 추가
  package.json
  src/components/CheckOrder/CheckBuyList.tsx
  src/components/Comment/CommentItem.tsx
  src/components/Loading.tsx
  src/components/Modal.tsx
  src/components/Total.tsx
  src/main.tsx
  src/pages/detail/detail.tsx
  src/store/detailStore.ts
Labels: enhancement

#196 ✨메인페이지 무한 스크롤
  index.html
  src/components/Layout/Footer.tsx
  src/hooks/useGetList.ts
  src/pages/main/main.tsx
Labels: feature

#197 feat[#192]: 기본 이미지 랜덤 출력
  src/pages/write/write.tsx
Labels: feature

#202 🐛 메인페이지 버그 및 게시글 없음 컴포넌트
  public/images/banner/banner3.png
  public/images/banner/banner4.png
  public/images/banner/banner5.png
  public/images/chef/sadChef.svg
  src/components/ImageSlide.tsx
  src/components/NoData.tsx
  src/components/Select.tsx
  src/components/TypeSelector.tsx
  src/constants/banner.ts
  src/constants/constants.ts
  src/pages/main/main.tsx
  src/pages/myPage/myPage.tsx
  src/store/listStateStore.ts
Labels: feature

#203 💄feat[175: 글 상세 - 댓글, 신청자 없을 때 마크업 추가
  src/components/CheckOrder/CheckBuyList.tsx
  src/components/Comment/Comment.tsx
  src/components/Comment/CommentItem.tsx
  src/components/ImageSlide.tsx
  src/components/ImageSlideDetail.tsx
  src/pages/detail/detail.tsx
  src/store/detailStore.ts
Labels: feature

#228 🐛bug[204]: 글 상세 로그인, 제목 특수문자 버그 수정
  src/components/kakaoAddr.tsx
  src/hooks/axiosInstance.ts
  src/pages/detail/detail.tsx
  src/pages/write/write.tsx
Labels: 🐛 bug

#229 🐛 메인페이지 상품 리스트 렌더링오류 해결
  public/images/arrow/next.svg
  public/images/arrow/prev.svg
  src/components/ImageSlide.tsx
  src/components/List.tsx
  src/components/Loading.tsx
  src/components/Total.tsx
  src/pages/login/login.tsx
  src/pages/main/main.tsx
  src/pages/myPage/myPage.tsx
  src/pages/signUp/signUp.tsx
  src/pages/write/write.tsx
Labels: 🐛 bug

#232 🐛bug: 글 상세 내부 빌드 오류 해결
  src/components/Comment/CommentAdd.tsx
  src/components/Total.tsx
  src/pages/detail/detail.tsx
Labels: 🐛 bug

#234 ✨ token 관리
  src/components/Layout/Footer.tsx
  src/hooks/axiosInstance.ts
  src/pages/myPage/myPage.tsx
Labels: ⚒️ enhancement

#241 [BUG] 다른 글 상세 페이지로 이동 시 최초 1회 버튼 안바뀌는 버그 해결
  src/pages/detail/detail.tsx
Labels: 🐛 bug

#250 🐛 토큰 및 유저정보 관리
  src/components/CheckOrder/CheckBuyList.tsx
  src/components/Comment/CommentAdd.tsx
  src/components/ImageUpload.tsx
  src/components/Layout/Footer.tsx
  src/components/Total.tsx
  src/hooks/axiosInstance.ts
  src/hooks/isDuplicate.ts
  src/hooks/useAxiosInstance.ts
  src/hooks/useGetList.ts
  src/hooks/useGetUserInfo.ts
  src/pages/detail/detail.tsx
  src/pages/login/login.tsx
  src/pages/myPage/modifyInfo.tsx
  src/pages/myPage/myPage.tsx
  src/pages/signUp/signUp.tsx
  src/pages/write/write.tsx
  src/store/authStore.ts
Labels: ⚒️ enhancement

#258 💄feat[243]: 글 상세 - 댓글 수정, 삭제 구현
  public/images/icons/more.svg
  src/components/Comment/Comment.tsx
  src/components/Comment/CommentAdd.tsx
  src/components/Comment/CommentItem.tsx
  src/components/Total.tsx
  src/pages/detail/detail.tsx
  src/store/detailStore.ts
Labels: ✨ feature

#268 🐛bug[#259]: 게시글 이동 간 버튼 오류 수정
  src/components/Comment/CommentItem.tsx
  src/pages/detail/detail.tsx
  src/store/detailStore.ts
Labels: 🐛 bug

#273 ✨알림기능 추가
  public/images/icons/notification.svg
  src/components/Layout/Footer.tsx
  src/hooks/useGetNotification.ts
  src/hooks/useRegisterNotification.ts
  src/pages/detail/detail.tsx
  src/pages/main/main.tsx
  src/pages/myPage/modifyInfo.tsx
  src/pages/myPage/myPage.tsx
  src/store/notificationStore.ts
Labels: ✨ feature

#274 ✨[feat] 글 상세 - 1차 qa
  src/components/CheckOrder/CheckBuyListItem.tsx
  src/components/Comment/CommentItem.tsx
Labels: ⚒️ enhancement

#278 ✨ 게시자가 신청자에게 메시지 전달 기능
  src/components/CheckOrder/CheckBuyList.tsx
  src/components/CheckOrder/CheckBuyListItem.tsx
  src/components/Layout/Footer.tsx
  src/components/Modal.tsx
  src/hooks/isDuplicate.ts
  src/hooks/useAxiosInstance.ts
  src/hooks/useGetNotification.ts
  src/pages/detail/detail.tsx
  src/pages/main/main.tsx
  src/pages/myPage/modifyInfo.tsx
Labels: ✨ feature

#285 🐛bug: 구매 현황 중 구매자 리스트 정렬 안맞는 현상 수정
  src/components/CheckOrder/CheckBuyListItem.tsx
Labels: 🐛 bug

#289 feat: 2차 배포 테스트
  public/images/arrow/next.svg
  public/images/arrow/prev.svg
  public/images/chef/forkChef.svg
  public/images/icons/more.svg
  public/images/icons/notification.svg
  src/components/CheckOrder/CheckBuyList.tsx
  src/components/CheckOrder/CheckBuyListItem.tsx
  src/components/Comment/Comment.tsx
  src/components/Comment/CommentAdd.tsx
  src/components/Comment/CommentItem.tsx
  src/components/ErrorPage.tsx
  src/components/ImageUpload.tsx
  src/components/Layout/Footer.tsx
  src/components/Loading.tsx
  src/components/Modal.tsx
  src/components/Picker.tsx
  src/components/PostType.tsx
  src/components/Select.tsx
  src/components/Total.tsx
  src/components/kakaoAddr.tsx
  src/constants/location.ts
  src/hooks/axiosInstance.ts
  src/hooks/isDuplicate.ts
  src/hooks/useAxiosInstance.ts
  src/hooks/useGetList.ts
  src/hooks/useGetNotification.ts
  src/hooks/useGetUserInfo.ts
  src/hooks/useRegisterNotification.ts
  src/pages/detail/detail.tsx
  src/pages/login/KakaoLogin.tsx
  src/pages/login/kakaoRedirect.tsx
  src/pages/login/login.tsx
  src/pages/main/main.tsx
  src/pages/myPage/modifyInfo.tsx
  src/pages/myPage/myPage.tsx
  src/pages/signUp/signUp.tsx
  src/pages/splash/splashStart.tsx
  src/pages/write/write.tsx
  src/router.tsx
  src/store/authStore.ts
  src/store/detailStore.ts
  src/store/notificationStore.ts
Labels: ✨ feature

#292 🐛 bug/이미지 가득차지 않던 오류 수정
  src/components/ImageSlide.tsx
Labels: 🐛 bug

#297 🐛 fix: QA 진행후 버그 및 스타일 수정
  api/dbinit-sample/openmarket/uploadFiles/geonwoo.png
  api/dbinit-sample/openmarket/uploadFiles/hyunjong.png
  api/dbinit-sample/openmarket/uploadFiles/sunjae.png
  api/dbinit-sample/openmarket/uploadFiles/yujin.png
  public/images/arrow/rightArrow.svg
  public/images/chef/noticeChef.svg
  src/components/Comment/Comment.tsx
  src/components/Comment/CommentItem.tsx
  src/components/ImageUpload.tsx
  src/components/KakaoMap.tsx
  src/components/List.tsx
  src/components/Picker.tsx
  src/components/PostType.tsx
  src/components/kakaoAddr.tsx
  src/hooks/useAxiosInstance.ts
  src/pages/detail/detail.tsx
  src/pages/main/main.tsx
  src/pages/myPage/modifyInfo.tsx
  src/pages/myPage/myPage.tsx
  src/pages/write/write.tsx
Labels: 🐛 bug

#300 🐛 fix/이미지 세로 크기 지정
  src/components/ImageSlide.tsx
  src/pages/detail/detail.tsx
Labels: 🐛 bug

#303 🐛 로그인 화면에서 알림 요청 제한
  src/components/Layout/Footer.tsx
  src/hooks/useAxiosInstance.ts
  src/hooks/useGetNotification.ts
Labels: 🐛 bug

#304 🐛 회원가입 페이지 예외 추가
  src/hooks/useGetNotification.ts
Labels: 🐛 bug

#308 ♻️ 메인페이지 상품리스트 코드 리팩토링 및 알림 제거
  src/pages/main/main.tsx
  src/pages/main/productList.tsx
Labels: 🐛 bug, ⚒️ enhancement, ✨ feature, 🚨 High

#315 🐛 회원정보 변경 프로필 사진 버그 수정
  src/components/Comment/CommentAdd.tsx
  src/pages/detail/detail.tsx
  src/pages/login/kakaoRedirect.tsx
  src/pages/main/main.tsx
  src/pages/myPage/modifyInfo.tsx
  src/pages/signUp/signUp.tsx
  src/pages/write/write.tsx
Labels: 🐛 bug, ⚒️ enhancement

#318 🐛 상품리스트 페이지 2이상 시 중첩 버그 해결
  src/components/TypeSelector.tsx
  src/pages/main/main.tsx
Labels: 🐛 bug

#324 🐛 메시지 오류 수정2
  src/components/CheckOrder/CheckBuyList.tsx
  src/components/CheckOrder/CheckBuyListItem.tsx
Labels: 🐛 bug
